version: "0.5"
log_level: info
log_length: 3000
log_configuration:
  rotation:
    max_size_mb: 1
    max_age_days: 3
    max_backups: 3
    compress: true
  fields_order: ["time", "level", "message"]
  disable_json: true
  timestamp_format: "06-01-02 15:04:05.000"
  no_metadata: false
  add_timestamp: true


environment:
  - 'PC_DEBUG=1'
log_location: ./pc.log
shell:
  shell_command: "bash"
  shell_argument: "-c"

processes:
  server:
    command: "python3 -m http.server 4040"
    is_tty: true

  kcalc:
    command: "kcalc"
    disabled: true

  bat_config:
    command: "cat process-compose.yaml"

  echos:
    command: "echo something"
